steps:
  # pull the latest from repo branch: development
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/peterchang04/projectmrest']
  - name: 'gcr.io/cloud-builders/git'
    args: ['checkout', 'development']
  # yarn globals
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['global', 'add', 'nodemon']
  # install package.json
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']
  # run tests
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['test']
  # build docker image locally
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build' '-t', 'gcr.io/projectmrest/development', '.']
  # push ready-to-deploy image to container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/projectmrest/development:$BRANCH_NAME:$BUILD_ID']
