version: 2
jobs:
  test:
    working_directory: ~/tmp
    docker:
      - image: peterchang04/projectmrest
    steps:
      - checkout
      - run: yarn
      - run: yarn test
workflows:
  version: 2
  dev_test_and_stage_on_commit:
    jobs:
      - test:
        filters:
          branches:
            only:
              - development
