version: 2
jobs:
  test:
    working_directory: ~/tmp
    docker:
      - image: peterchang04/projectmrest
    steps:
      - checkout
      - run: yarn
      - run: yarn test
workflows:
  version: 2
  # this build on circleci exists only to run and verify the commit to development + emails as necessary
  dev_test_and_stage_on_commit:
    jobs:
      - test:
          filters:
            branches:
              only: development
